#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$appname.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_backup "/etc/php/7.1/fpm/pool.d/$appname.conf"
ynh_backup "/etc/php/7.1/fpm/conf.d/20-$appname.ini"

#=================================================
# BACKUP OF THE SQL BDD
#=================================================

if [ $sql -eq 1 ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app mysqlpwd)
	ynh_mysql_dump_db "$db_name" > ($db_name).sql
	CHECK_SIZE "($db_name).sql"
fi
