#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors	# Active trap to stop the script if an error is detected.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
sql=$YNH_APP_ARG_SQL
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

parent_dir=/var/www/$app
#directory="${domain//-/_}_$(echo $path_url | cut -d '/' -f 2)"
appname=$app
final_path=$parent_dir
# For this app, app matches the label, as usual and also in the name of the application.
# Check that the destination folder is not already in use.
if [ -e "$final_path" ]
then
	ynh_die "This path already contains a folder"
fi

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path $path_url)


# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app appname $appname
ynh_app_setting_set $app ftp_user $admin
ynh_app_setting_set $app final_path $final_path
ynh_app_setting_set $app parent_dir $parent_dir
ynh_app_setting_set $app sql $sql

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# SETUP SSOWAT
#=================================================

if [ $is_public -eq 1 ]
then
	ynh_app_setting_set $app skipped_uris "/"
fi

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE FINAL PATH
#=================================================

# Create the parent webapp folder for the user
if test ! -d $parent_dir
then	# Create the parent folder only if it does not exist
	mkdir $parent_dir
	# Set permissions
	chmod 755 -R $parent_dir
	chown -R root: $parent_dir
else
	ynh_print_info "Creating the $ parent_dir folder skipped, the folder already exists." >&2
fi

# Copy files to the right place
mkdir -p $final_path

# Check if pure-ftpd is already installed
if test -f /usr/sbin/pure-ftpd-ldap
then	# If so, check if net2ftp is also installed.
	if test -d $parent_dir/netftp
	then
		# Change admin ID in configurations
		netftp_path=/ftp_$app_$admin
		ynh_replace_string "__FTPUSER__" "$admin" ../sources/info_ftp.html
		ynh_replace_string "__HOST__" "$domain" ../sources/info_ftp.html
		ynh_replace_string "__NET2FTP__" "$netftp_path" ../sources/info_ftp.html
		ynh_replace_string "__PORT__" "$(cat /etc/pure-ftpd/conf/Bind)" ../sources/info_ftp.html
		cp ../sources/info_ftp.html $final_path/info_ftp.html	# Creates the info_ftp.html with the one integrating the ftp information
	fi
fi

#=================================================
# CREATE A SQL BDD
#=================================================

if [ $sql -eq 1 ]
then
	db_name=$(ynh_sanitize_dbid $appname)db
	db_user=$(ynh_sanitize_dbid $appname)dbuser
	ynh_app_setting_set $app db_name $db_name
	ynh_mysql_setup_db $db_user $db_name
	echo "DB_NAME= $db_name" | tee "$final_path/db_info.txt"
	echo "DB_USER= $db_user" | tee -a "$final_path/db_info.txt"
	echo "DB_PASSWORD= $db_pwd" | tee -a "$final_path/db_info.txt"
	echo "DB_HOST= localhost" | tee -a "$final_path/db_info.txt"
fi

#=================================================
# CREATE DEDICATED USER
#=================================================

ynh_system_user_create $appname	# Create a dedicated system user for the app.

ynh_install_php71

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# Due to the use of $ appname, it is not possible to use ynh_fpm_config.
finalphpconf="/etc/php/7.1/fpm/pool.d/$appname.conf"
cp ../conf/php-fpm.conf "$finalphpconf"

ynh_replace_string "__NAMETOCHANGE__" "$appname" "$finalphpconf"
ynh_replace_string "__FINALPATH__" "$final_path" "$finalphpconf"
ynh_replace_string "__USER__" "$appname" "$finalphpconf"

chown root: "$finalphpconf"

finalphpini="/etc/php/7.1/fpm/conf.d/20-$appname.ini"
cp ../conf/php-fpm.ini "$finalphpini"
chown root: "$finalphpini"

systemctl reload php7.1-fpm

#=================================================
# NGINX CONFIGURATION
#=================================================

# Due to the use of $ appname, it is not possible to use ynh_nginx_config

finalnginxconf="/etc/nginx/conf.d/$domain.d/$appname.conf"
cp ../conf/nginx.conf "$finalnginxconf"

if [ "$path_url" != "/" ]
then
	ynh_replace_string "^#sub_path_only" "" "$finalnginxconf"
fi
ynh_replace_string "__PATH__/" "${path_url%/}/" "$finalnginxconf"
ynh_replace_string "__PATH__" "$path_url" "$finalnginxconf"
ynh_replace_string "__FINALPATH__" "$final_path" "$finalnginxconf"
ynh_replace_string "__APPNAME__" "$appname" "$finalnginxconf"

#=================================================
# GENERIC FINALISATION
#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

chmod 755 $final_path
#chown -R $admin:$appname $final_path
chown -R $appname:$appname $final_path

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

if [ "$sql" != "0" ]
then
	sql_infos="
You ask for an database, please find here the informations about this SQL database.
$(cat "$final_path/db_info.txt")
"
else
	sql_infos=""
fi

message="The solution is now deployed. Proceed for configuration of the solution. For database use:
$sql_infos
The Solution is placed in this directory, $final_path

Kindly refer to info_ftp.html and info_noftp.html files for deployment status information.

You can find a standard nginx configuration in $finalnginxconf and a standard php config in $finalphpconf and $finalphpini

If you facing an issue or want to improve this app, please open a new issue in this project: http://support.deifysolutions.com"

ynh_send_readme_to_admin "$message" "$admin"
