#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

admin=$(ynh_app_setting_get $app ftp_user)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)
final_path=$(ynh_app_setting_get $app final_path)
parent_dir=$(ynh_app_setting_get $app parent_dir)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE SQL BDD
#=================================================

if [ "$sql" -eq "1" ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	ynh_mysql_remove_db $db_name $db_name	# Deleting the database and the associated user.
fi

#=================================================
# REMOVE THE MAIN DIR OF THE APP
#=================================================

ynh_secure_remove "$final_path"	# Deleting the webapp folder

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================

app=$appname	# Use appname for FPM and nginx
ynh_remove_nginx_config	# Deleting the nginx configuration

#=================================================
# REMOVE THE PHP-FPM CONFIGURATION
#=================================================

#ynh_remove_fpm_config	# Deleting php-fpm pool configuration
ynh_remove_php7.1-fpm_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE PARENT DIR
#=================================================
#Check if the parent folder is empty. Which means that all webapps have been uninstalled. As well as the net2ftp ftp client.
if [ -e "$parent_dir" ]
then
	if test -z "$(ls $parent_dir | head -n1)"
	then
		ynh_secure_remove $parent_dir
	fi
fi

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $appname
